CREATE DATABASE IF NOT EXISTS fractal_maintenance;
USE fractal_maintenance;

-- 1. Table: Tickets
CREATE TABLE IF NOT EXISTS Tickets (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(150) NOT NULL,
    Equipment VARCHAR(50) NOT NULL,
    Description TEXT NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT CHK_Ticket_Status CHECK (Status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED'))
) ENGINE=InnoDB;

-- 2. Table: TicketHistories (1-N Relationship)
CREATE TABLE IF NOT EXISTS TicketHistories (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TicketId INT NOT NULL,
    PreviousStatus VARCHAR(20) NULL,
    NewStatus VARCHAR(20) NOT NULL,
    Comment TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TicketHistories_Tickets FOREIGN KEY (TicketId) 
        REFERENCES Tickets(Id) ON DELETE CASCADE
) ENGINE=InnoDB;